//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectcv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEXPERIENCE
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string SUBTITLE { get; set; }
        public string DATE { get; set; }
        public string DETAILS { get; set; }
    }
}
